### ISSUE TITLE
authorize user Piwigo-TranslationTeam

### ISSUE THREAD

**Issue by ddtddt** [phweyland/UpdateAlbum-Piwigo#3]
For add your project on https://piwigo.org/translate, can you give acces to user Piwigo-TranslationTeam and say me it's ok ;-)

**Comment by phweyland** [comment]
Sorry for the delay.
My login still works on https://piwigo.org/ but not on https://piwigo.org/translate. Do I miss something ?

**Comment by phweyland** [comment]
Ok, I've updated my profile and I'm logged in. But I can just choose language or one of 5 projects.
Is that still a valid request ?
Thanks

**Comment by phweyland** [comment]
Done.
